services:
  prueba-tecnica-gux:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    stdin_open: true
    tty: true # Keeps the container running for debugging
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - gux-network

  postgres_db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: prueba_tecnica_gux
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - gux-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h postgres_db -U postgres"]
      interval: 5s
      timeout: 2s
      retries: 20

networks:
  gux-network:
    name: gux-network
