import type { Metadata } from "next";
import "./globals.css";
import "@fontsource-variable/merriweather-sans";

export const metadata: Metadata = {
  title: "Prueba técnica Gux",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">{children}</body>
    </html>
  );
}
